version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

  # Managed by Renovate
  # - package-ecosystem: docker
  #   directory: "/"
  #   schedule:
  #     interval: daily
