name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build variants
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.8.1]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Generate variants
        if: github.ref != 'refs/heads/dist'
        run: ./bin/generate-variants.sh ${{ matrix.version }} dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          publish_branch: dist
          enable_jekyll: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
