name: Docker CI

on: [push, pull_request]

jobs:
  testing:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [fpm-alpine, fpm, apache]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Generate variants
        if: github.ref != 'refs/heads/dist'
        run: ./bin/generate-variants.sh

      - name: Prepare Tools
        run: git clone https://github.com/docker-library/official-images.git ~/official-images

      - name: Build and Test
        run: |
          VERSION="$(head -n 1 yourls_version)"
          docker build -t "${IMAGE}:${VERSION}-${VARIANT}" "${VARIANT}"
          ~/official-images/test/run.sh "${IMAGE}"
        env:
          IMAGE: yourls
          VARIANT: ${{ matrix.variant }}

      - run: docker images
