name: Release

on:
  - push
#    tags:
#      - '*'

jobs:
  docker:
    name: Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [fpm-alpine, fpm, apache]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Use Docker builder
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.variant }}/
          file: ./${{ matrix.variant }}/Dockerfile
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ secrets.REGISTRY_IMAGE }}
          tags: |
            ghcr.io/${{ secrets.REGISTRY_IMAGE }}:${{ matrix.variant }}
#            ghcr.io/${{ secrets.REGISTRY_IMAGE }}:${{ github.ref }}
          push: true
